Create the home page (Html file)
GSG-FC02/Booklopedia-Project pull request #14
Opened 2021-04-13 15:20 UTC by Maramfathi99

Relates #4
This page contains the HTML structure.

2021-04-13 20:03 UTC, sara219 requested changes

2021-04-13 20:03 UTC, sara219 commented on index.html
> +    <link rel="stylesheet" href="style.css" />
your file name is `home.css` not `style.css`

```suggestion
    <link rel="stylesheet" href="home.css" />
```

2021-04-13 20:03 UTC, sara219 commented on index.html
> +      <img src="Component.png" />
the path for the image is not right.
the component image is inside the images folder, not in the root as the HTML file.

```suggestion
      <img src="./image/Component.png" alt="" />
```

![Screenshot from 2021-04-13 22-34-30](https://user-images.githubusercontent.com/47992412/114610349-749fca80-9ca8-11eb-8722-35ef17c4b483.png)

2021-04-13 20:03 UTC, sara219 commented on home.css
> +  height: 233px;
the picture has both height and width set, which distorts it a little. I think you should select only the width

![Screenshot from 2021-04-13 22-55-42](https://user-images.githubusercontent.com/47992412/114613147-a36b7000-9cab-11eb-8804-e25588b43d7e.png)

2021-04-13 20:03 UTC, sara219 commented on home.css
> +    background: #191927;
you can clearly see the color difference between the background of the image and the other color

![Screenshot from 2021-04-13 23-00-42](https://user-images.githubusercontent.com/47992412/114613588-3a382c80-9cac-11eb-9188-3f680bdbfedd.png)

use `#211c2c`
```suggestion
    background: #211c2c;
```

2021-04-13 22:15 UTC, sara219 approved these changes
💯

2021-04-14 03:42 UTC, Raghad-Mezied approved these changes

2021-04-14 05:53 UTC, merged